#!/usr/bin/env python2

import pandas as pd
import numpy as np
import data_commons as dtc
import dl_commons as dlc
import hyper_params as hp
import os


hyper = hp.make_hyper({'num_gpus':2, 'build_image_context':0})
# cal1 = hp.CALSTMParams({'m':64})
# cal2 = hp.CALSTMParams({'m':cal1.decoder_lstm.layers_units[-1]})
f = '../data/scratch.pkl'

# orig_args = dlc.Properties({
#     'B': 40,
#     'MeanSumAlphaEquals1': False,
#     'NOTE': 'CHECK # of LSTM LAYERS',
#     'StartTokenID': 'dl_commons.equalto object at 0x7f40062015d0',
#     'assert_whole_batch': False,
#     'beamsearch_length_penalty': 1.0,
#     'build_image_context': 0,
#     'ctc_beam_width': 10,
#     'data_dir': '../data',
#     'doTrain': True,
#     'doValidate': False,
#     'dropout': None,
#     'generated_data_dir': '../data/generated2',
#     'image_dir': '../data/formula_images_2',
#     'logdir': 'tb_metrics/2017-09-26 22-40-18 PDT',
#     'logger': 'logging.Logger object at 0x7f4006201410',
#     'make_training_accuracy_graph': False,
#     'num_epochs': -1,
#     'num_gpus': 2,
#     'num_steps': -1,
#     'pLambda': 0.005,
#     'print_batch': True,
#     'print_steps': 50,
#     'rLambda': 5e-05,
#     'restore_from_checkpoint': False,
#     'seq2seq_beam_width': 10,
#     'squash_input_seq': True,
#     'sum_logloss': False,
#     'swap_memory': False,
#     'tb': {'tb_activations': 'Activations',
#             'tb_biases': 'Biases',
#             'tb_logdir': 'tb_metrics',
#             'tb_weights': 'Weights'},
#     'tf_session_allow_growth': False,
#     'use_ctc_loss': False,
#     'valid_epochs': 1.0,
#     'valid_frac': 0.05
# })

# orig_hyper = dlc.Properties({
#     'B': 40,
#     'CALSTM_STACK': [{'B': 40,
#                     'CTCBlankTokenID': 556,
#                     'D': 512,
#                     'H': 3,
#                     'K': 557,
#                     'L': 99,
#                     'MaxSeqLen': 151,
#                     'NullTokenID': 0,
#                     'SpaceTokenID': 556,
#                     'StartTokenID': 556,
#                     'W': 33,
#                     'att_layers': {'activation_fn': '<function tanh at 0x7f4079de36e0>',
#                                     'biases_initializer': '<tensorflow.python.ops.init_ops.Zeros object at 0x7f40061ea810>',
#                                     'biases_regularizer': None,
#                                     'dropout': None,
#                                     'layers_units': [512],
#                                     'normalizer_fn': None,
#                                     'op_name': 'MLP',
#                                     'tb': {'tb_activations': 'Activations',
#                                             'tb_biases': 'Biases',
#                                             'tb_logdir': 'tb_metrics',
#                                             'tb_weights': 'Weights'},
#                                     'weights_initializer': '<function _initializer at 0x7f40062d3b18>',
#                                     'weights_regularizer': '<function l2 at 0x7f406bd2b8c0>'},
#                     'att_share_weights': True,
#                     'att_weighted_gather': True,
#                     'biases_initializer': '<tensorflow.python.ops.init_ops.Zeros object at 0x7f40061ea810>',
#                     'biases_regularizer': None,
#                     'build_image_context': 0,
#                     'decoder_lstm': {'B': 40,
#                                         'dropout': None,
#                                         'dtype': 'tf.float32',
#                                         'forget_bias': 1.0,
#                                         'i': 576,
#                                         'layers_units': [1000, 1000],
#                                         'op_name': 'LSTMWrapper',
#                                         'tb': {'tb_activations': 'Activations',
#                                             'tb_biases': 'Biases',
#                                             'tb_logdir': 'tb_metrics',
#                                             'tb_weights': 'Weights'},
#                                         'type': 'lstm',
#                                         'use_peephole': True,
#                                         'weights_initializer': '<function _initializer at 0x7f40062d3b18>',
#                                         'weights_regularizer': '<function l2 at 0x7f406bd2b8c0>'},
#                     'dropout': None,
#                     'dtype': 'tf.float32',
#                     'dtype_np': '<type numpy.float32>',
#                     'image_shape_unframed': [120, 1075, 3],
#                     'int_type': 'tf.int32',
#                     'int_type_np': '<type numpy.int32>',
#                     'logger': '<logging.Logger object at 0x7f4006201410>',
#                     'm': 64,
#                     'n': 1000,
#                     'rLambda': 5e-05,
#                     'tb': {'tb_activations': 'Activations',
#                             'tb_biases': 'Biases',
#                             'tb_logdir': 'tb_metrics',
#                             'tb_weights': 'Weights'},
#                     'use_peephole': True,
#                     'weights_initializer': '<function _initializer at 0x7f40062d3b18>',
#                     'weights_regularizer': '<function l2 at 0x7f406bd2b8c0>'}],
#     'CONVNET': None,
#     'CTCBlankTokenID': 556,
#     'D': 512,
#     'DecodingSlack': 20,
#     'H': 3,
#     'K': 557,
#     'L': 99,
#     'MaxDecodeLen': 171,
#     'MaxSeqLen': 151,
#     'MeanSumAlphaEquals1': False,
#     'NullTokenID': 0,
#     'SpaceTokenID': 556,
#     'StartTokenID': 556,
#     'W': 33,
#     'adam_alpha': 0.0001,
#     'assert_whole_batch': False,
#     'beamsearch_length_penalty': 1.0,
#     'biases_initializer': '<tensorflow.python.ops.init_ops.Zeros object at 0x7f40061ea810>',
#     'biases_regularizer': None,
#     'build_image_context': 0,
#     'ctc_beam_width': 10,
#     'data_reader_B': 80,
#     'dropout': None,
#     'dtype': 'tf.float32',
#     'dtype_np': '<type numpy.float32>',
#     'embeddings_initializer': '<function _initializer at 0x7f40062d3b18>',
#     'embeddings_regularizer': '<function l2 at 0x7f406bd2b8c0>',
#     'image_frame_width': 0,
#     'image_shape': [120, 1075, 3],
#     'image_shape_unframed': [120, 1075, 3],
#     'init_model': {'activation_fn': '<function relu at 0x7f4079eeaa28>',
#                 'biases_initializer': '<tensorflow.python.ops.init_ops.Zeros object at 0x7f40061ea810>',
#                 'biases_regularizer': None,
#                 'dropout': None,
#                 'layers_units': [512],
#                 'normalizer_fn': None,
#                 'op_name': 'MLP',
#                 'tb': {'tb_activations': 'Activations',
#                         'tb_biases': 'Biases',
#                         'tb_logdir': 'tb_metrics',
#                         'tb_weights': 'Weights'},
#                 'weights_initializer': '<function _initializer at 0x7f40062d3b18>',
#                 'weights_regularizer': '<function l2 at 0x7f406bd2b8c0>'},
#     'init_model_final_layers': {'activation_fn': '<function tanh at 0x7f4079de36e0>',
#                                 'biases_initializer': '<tensorflow.python.ops.init_ops.Zeros object at 0x7f40061ea810>',
#                                 'biases_regularizer': None,
#                                 'dropout': None,
#                                 'normalizer_fn': None,
#                                 'num_units': None,
#                                 'tb': {'tb_activations': 'Activations',
#                                     'tb_biases': 'Biases',
#                                     'tb_logdir': 'tb_metrics',
#                                     'tb_weights': 'Weights'},
#                                 'weights_initializer': '<function _initializer at 0x7f40062d3b18>',
#                                 'weights_regularizer': '<function l2 at 0x7f406bd2b8c0>'},
#     'input_queue_capacity': 6,
#     'int_type': 'tf.int32',
#     'int_type_np': '<type numpy.int32>',
#     'k': 5,
#     'logger': '<logging.Logger object at 0x7f4006201410>',
#     'm': 64,
#     'n': 1000,
#     'no_ctc_merge_repeated': True,
#     'no_towers': False,
#     'num_gpus': 2,
#     'optimizer': '<tensorflow.python.training.adam.AdamOptimizer object at 0x7f40062223d0>',
#     'output_follow_paper': True,
#     'output_layers': {'activation_fn': '<function relu at 0x7f4079eeaa28>',
#                     'biases_initializer': '<tensorflow.python.ops.init_ops.Zeros object at 0x7f40061ea810>',
#                     'biases_regularizer': None,
#                     'dropout': None,
#                     'layers_units': [64, 557],
#                     'normalizer_fn': None,
#                     'op_name': 'yLogits_MLP',
#                     'tb': {'tb_activations': 'Activations',
#                             'tb_biases': 'Biases',
#                             'tb_logdir': 'tb_metrics',
#                             'tb_weights': 'Weights'},
#                     'weights_initializer': '<function _initializer at 0x7f40062d3b18>',
#                     'weights_regularizer': '<function l2 at 0x7f406bd2b8c0>'},
#     'pLambda': 0.005,
#     'rLambda': 5e-05,
#     'seq2seq_beam_width': 10,
#     'squash_input_seq': True,
#     'sum_logloss': False,
#     'swap_memory': False,
#     'tb': {'tb_activations': 'Activations',
#         'tb_biases': 'Biases',
#         'tb_logdir': 'tb_metrics',
#         'tb_weights': 'Weights'},
#     'tf_session_allow_growth': False,
#     'use_ctc_loss': False,
#     'use_peephole': True,
#     'weights_initializer': '<function _initializer at 0x7f40062d3b18>',
#     'weights_regularizer': '<function l2 at 0x7f406bd2b8c0>'})

# mod_args = dlc.Properties({'B': 40,
#     'MeanSumAlphaEquals1': False,
#     'NOTE': 'CHECK # of LSTM LAYERS',
#     'StartTokenID': '<dl_commons.equalto object at 0x7f5cdf2e5650>',
#     'assert_whole_batch': False,
#     'beamsearch_length_penalty': 1.0,
#     'build_image_context': 0,
#     'ctc_beam_width': 10,
#     'data_dir': '../data',
#     'doTrain': True,
#     'doValidate': False,
#     'dropout': None,
#     'generated_data_dir': '../data/generated2',
#     'image_dir': '../data/formula_images_2',
#     'logdir': 'tb_metrics/2017-10-08 12-26-45 PDT',
#     'logger': '<logging.Logger object at 0x7f5cdf2f4410>',
#     'make_training_accuracy_graph': False,
#     'num_epochs': -1,
#     'num_gpus': 2,
#     'num_steps': -1,
#     'pLambda': 0.005,
#     'print_batch': True,
#     'print_steps': 50,
#     'rLambda': 5e-05,
#     'restore_from_checkpoint': False,
#     'seq2seq_beam_width': 10,
#     'squash_input_seq': True,
#     'storedir': 'tb_metrics/2017-10-08 12-26-45 PDT/store',
#     'sum_logloss': False,
#     'swap_memory': False,
#     'tb': {'tb_activations': 'Activations',
#         'tb_biases': 'Biases',
#         'tb_logdir': 'tb_metrics',
#         'tb_weights': 'Weights'},
#     'tf_session_allow_growth': False,
#     'use_ctc_loss': False,
#     'valid_epochs': 1.0,
#     'valid_frac': 0.05})

# mod_hyper = dlc.Properties({'B': 40,
#     'CALSTM_STACK': [{'B': 40,
#                     'CTCBlankTokenID': None,
#                     'D': 512,
#                     'H': 3,
#                     'K': 557,
#                     'L': 99,
#                     'MaxSeqLen': 151,
#                     'NullTokenID': 0,
#                     'SpaceTokenID': 556,
#                     'StartTokenID': 556,
#                     'W': 33,
#                     'att_layers': {'activation_fn': '<function tanh at 0x7f5ceea85668>',
#                                     'biases_initializer': '<tensorflow.python.ops.init_ops.Zeros object at 0x7f5cdf33b610>',
#                                     'biases_regularizer': None,
#                                     'dropout': None,
#                                     'layers_units': [512],
#                                     'normalizer_fn': None,
#                                     'op_name': 'MLP',
#                                     'tb': {'tb_activations': 'Activations',
#                                             'tb_biases': 'Biases',
#                                             'tb_logdir': 'tb_metrics',
#                                             'tb_weights': 'Weights'},
#                                     'weights_initializer': '<function _initializer at 0x7f5cdf338668>',
#                                     'weights_regularizer': '<function l2 at 0x7f5d66613230>'},
#                     'att_share_weights': True,
#                     'att_weighted_gather': True,
#                     'biases_initializer': '<tensorflow.python.ops.init_ops.Zeros object at 0x7f5cdf33b610>',
#                     'biases_regularizer': None,
#                     'build_image_context': 0,
#                     'decoder_lstm': {'B': 40,
#                                         'dropout': None,
#                                         'dtype': 'tf.float32',
#                                         'forget_bias': 1.0,
#                                         'i': 576,
#                                         'layers_units': [1000, 1000],
#                                         'op_name': 'LSTMWrapper',
#                                         'tb': {'tb_activations': 'Activations',
#                                             'tb_biases': 'Biases',
#                                             'tb_logdir': 'tb_metrics',
#                                             'tb_weights': 'Weights'},
#                                         'type': 'lstm',
#                                         'use_peephole': True,
#                                         'weights_initializer': '<function _initializer at 0x7f5cdf338668>',
#                                         'weights_regularizer': '<function l2 at 0x7f5d66613230>'},
#                     'dropout': None,
#                     'dtype': 'tf.float32',
#                     'dtype_np': '<type numpy.float32>',
#                     'image_shape_unframed': [120, 1075, 3],
#                     'int_type': 'tf.int32',
#                     'int_type_np': '<type numpy.int32>',
#                     'logger': None,
#                     'm': 64,
#                     'n': 1000,
#                     'rLambda': 5e-05,
#                     'tb': {'tb_activations': 'Activations',
#                             'tb_biases': 'Biases',
#                             'tb_logdir': 'tb_metrics',
#                             'tb_weights': 'Weights'},
#                     'use_ctc_loss': False,
#                     'use_peephole': True,
#                     'weights_initializer': '<function _initializer at 0x7f5cdf338668>',
#                     'weights_regularizer': '<function l2 at 0x7f5d66613230>'}],
#     'CONVNET': None,
#     'CTCBlankTokenID': None,
#     'D': 512,
#     'DecodingSlack': 20,
#     'H': 3,
#     'K': 557,
#     'L': 99,
#     'MaxDecodeLen': 171,
#     'MaxSeqLen': 151,
#     'MeanSumAlphaEquals1': False,
#     'NullTokenID': 0,
#     'SpaceTokenID': 556,
#     'StartTokenID': 556,
#     'W': 33,
#     'adam_alpha': 0.0001,
#     'assert_whole_batch': False,
#     'beamsearch_length_penalty': 1.0,
#     'biases_initializer': '<tensorflow.python.ops.init_ops.Zeros object at 0x7f5cdf33b610>',
#     'biases_regularizer': None,
#     'build_image_context': 0,
#     'ctc_beam_width': 10,
#     'data_reader_B': 80,
#     'dropout': None,
#     'dtype': 'tf.float32',
#     'dtype_np': '<type numpy.float32>',
#     'embeddings_initializer': '<function _initializer at 0x7f5cdf338668>',
#     'embeddings_regularizer': '<function l2 at 0x7f5d66613230>',
#     'image_frame_width': 0,
#     'image_shape': [120, 1075, 3],
#     'image_shape_unframed': [120, 1075, 3],
#     'init_model': {'activation_fn': '<function relu at 0x7f5ceebeb9b0>',
#                     'biases_initializer': '<tensorflow.python.ops.init_ops.Zeros object at 0x7f5cdf33b610>',
#                     'biases_regularizer': None,
#                     'dropout': None,
#                     'layers_units': [512],
#                     'normalizer_fn': None,
#                     'op_name': 'MLP',
#                     'tb': {'tb_activations': 'Activations',
#                         'tb_biases': 'Biases',
#                         'tb_logdir': 'tb_metrics',
#                         'tb_weights': 'Weights'},
#                     'weights_initializer': '<function _initializer at 0x7f5cdf338668>',
#                     'weights_regularizer': '<function l2 at 0x7f5d66613230>'},
#     'init_model_final_layers': {'activation_fn': '<function tanh at 0x7f5ceea85668>',
#                                 'biases_initializer': '<tensorflow.python.ops.init_ops.Zeros object at 0x7f5cdf33b610>',
#                                 'biases_regularizer': None,
#                                 'dropout': None,
#                                 'normalizer_fn': None,
#                                 'num_units': None,
#                                 'tb': {'tb_activations': 'Activations',
#                                         'tb_biases': 'Biases',
#                                         'tb_logdir': 'tb_metrics',
#                                         'tb_weights': 'Weights'},
#                                 'weights_initializer': '<function _initializer at 0x7f5cdf338668>',
#                                 'weights_regularizer': '<function l2 at 0x7f5d66613230>'},
#     'input_queue_capacity': 6,
#     'int_type': 'tf.int32',
#     'int_type_np': '<type numpy.int32>',
#     'k': 5,
#     'logger': '<logging.Logger object at 0x7f5cdf2f4410>',
#     'm': 64,
#     'n': 1000,
#     'no_ctc_merge_repeated': True,
#     'no_towers': False,
#     'num_gpus': 2,
#     'optimizer': '<tensorflow.python.training.adam.AdamOptimizer object at 0x7f5cdf2f43d0>',
#     'output_follow_paper': True,
#     'output_layers': {'activation_fn': '<function relu at 0x7f5ceebeb9b0>',
#                     'biases_initializer': '<tensorflow.python.ops.init_ops.Zeros object at 0x7f5cdf33b610>',
#                     'biases_regularizer': None,
#                     'dropout': None,
#                     'layers_units': [64, 557],
#                     'normalizer_fn': None,
#                     'op_name': 'yLogits_MLP',
#                     'tb': {'tb_activations': 'Activations',
#                             'tb_biases': 'Biases',
#                             'tb_logdir': 'tb_metrics',
#                             'tb_weights': 'Weights'},
#                     'weights_initializer': '<function _initializer at 0x7f5cdf338668>',
#                     'weights_regularizer': '<function l2 at 0x7f5d66613230>'},
#     'pLambda': 0.005,
#     'rLambda': 5e-05,
#     'seq2seq_beam_width': 10,
#     'squash_input_seq': True,
#     'sum_logloss': False,
#     'swap_memory': False,
#     'tb': {'tb_activations': 'Activations',
#             'tb_biases': 'Biases',
#             'tb_logdir': 'tb_metrics',
#             'tb_weights': 'Weights'},
#     'tf_session_allow_growth': False,
#     'use_ctc_loss': False,
#     'use_peephole': True,
#     'weights_initializer': '<function _initializer at 0x7f5cdf338668>',
#     'weights_regularizer': '<function l2 at 0x7f5d66613230>'})

